//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGSKFirst.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.AnswerSelectedOption = new HashSet<AnswerSelectedOption>();
        }
    
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string AnswerTxt { get; set; }
        public int InterviewId { get; set; }
        public Nullable<int> SelectedOptionId { get; set; }
    
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerSelectedOption> AnswerSelectedOption { get; set; }
        public virtual Interview Interview { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
    }
}
